# Generated by Django 4.2.7 on 2023-11-25 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviews_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.customer'),
        ),
    ]
