# Generated by Django 4.2.7 on 2023-12-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('PR', 'Preparing'), ('OW', 'On The Way')], default='p', max_length=2),
        ),
    ]
