# Generated by Django 4.2.7 on 2023-12-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('PR', 'Preparing'), ('OW', 'On The Way'), ('C', 'Completed')], default='P', max_length=2),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
