# Generated by Django 4.2.7 on 2023-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_address_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='NO', upload_to='store/customer/images'),
        ),
    ]
