# Generated by Django 4.2.7 on 2023-12-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customer_image_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('PR', 'Preparing'), ('OW', 'On The Way'), ('C', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2),
        ),
    ]
